version: "3.8"
services:
  leader:
    build:
      dockerfile: Dockerfile.leader
    command:
      - jkv
      - --volumes
      - jkv-volume-1:8000,jkv-volume-2:8000,jkv-volume-3:8000
    ports:
      - "3000:8000"
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - RUST_LOG=warn
  volume:
    deploy:
      replicas: 3
    build:
      dockerfile: Dockerfile.volume
